### ISSUE TITLE
After signup form data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Match-my-university#47]
After click signup button the data entered in the signup form should clear

[screen-capture (10).webm](https://github.com/antonym8/Match-my-university/assets/142376069/33630ff8-91a4-4f44-81d1-2484d48e8fac)

**Comment by M8Balaji** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed

![Screenshot (482)](https://github.com/antonym8/Match-my-university/assets/142376069/6c5dff00-f201-4065-b1d1-1507bf6a6b28)
